### PR TITLE
bulk_indexer: track all response status codes

### LINKED ISSUE #172: Missing bulk request metrics on error
The existing handling of bulk request error may miss metrics when the request itself returns an error. e.g. a 403 bulk request response will not be tracked under failed client.

### PR DESCRIPTION
**Pull request by marclop**
Updates the bulk_indexer to track all response status codes and report them appropriately as metrics. Also refactors tests to make them more succinct.

Closes #172

### CODE REVIEW

File: bulk_indexer.go [hunk 1]
```diff
@@ -530,10 +539,14 @@ func indexnth(s []byte, nth int, sep rune) int {
...
 }
 
-type errorTooManyRequests struct {
-	res *esapi.Response
+type errorFlushFailed struct {
+	resp        string
+	statusCode  int
+	tooMany     bool
+	clientError bool
+	serverError bool
```
Comment (inge4pres) [inline bulk_indexer.go:547]: nice 👍🏼

Comment (inge4pres) [reply bulk_indexer.go:547]: one other option would be to have a typed error for each case, and then wrapping them into an error returned on the specific branch, but we can always change that later

**Review by inge4pres — APPROVED** [review]
Thanks 👍🏼

File: appender_test.go [hunk 2]
```diff
@@ -671,67 +671,60 @@ func TestAppenderFlushBytes(t *testing.T) {
...
+			if sc == 429 {
+				wantStats.TooManyRequests = 1
+			} else {
+				if sc >= 500 {
+					wantStats.FailedServer = 1
+				} else {
+					wantStats.FailedClient = 1
+				}
+			}
+		}
```
Comment (carsonip) [inline appender_test.go:713]:
```suggestion
		wantStats := docappender.Stats{
			Added:                  2,
			Active:                 0,
			BulkRequests:           1,
			Failed:                 2,
			AvailableBulkRequests:  10,
			BytesTotal:             bytesTotal,
			BytesUncompressedTotal: bytesUncompressedTotal,
		}
		if sc >= 400 {
			if sc == 429 {
				wantStats.TooManyRequests = 2
			} else {
				if sc >= 500 {
					wantStats.FailedServer = 2
				} else {
					wantStats.FailedClient = 2
				}
			}
```

File: appender_test.go [hunk 3]
```diff
@@ -671,67 +671,60 @@ func TestAppenderFlushBytes(t *testing.T) {
...
-		Added:                  1,
-		Active:                 0,
-		BulkRequests:           1,
-		Failed:                 1,
-		AvailableBulkRequests:  10,
-		BytesTotal:             bytesTotal,
-		BytesUncompressedTotal: bytesUncompressedTotal,
-	}, stats)
-}
+		addMinimalDoc(t, indexer, "logs-foo-testing")
```
Comment (carsonip) [inline appender_test.go:688]:
```suggestion
                // Send 2 docs, ensure that metrics are always in the unit of documents, not requests.
		addMinimalDoc(t, indexer, "logs-foo-testing")
		addMinimalDoc(t, indexer, "logs-foo-testing")
```

**Review by carsonip — COMMENTED** [review]
nit to test number of docs != requests to ensure that the right unit is used.

File: bulk_indexer.go [hunk 4]
```diff
@@ -351,10 +351,19 @@ func (b *BulkIndexer) Flush(ctx context.Context) (BulkIndexerResponseStat, error
 	b.bytesUncompFlushed = bytesUncompFlushed
 	var resp BulkIndexerResponseStat
 	if res.IsError() {
-		if res.StatusCode == http.StatusTooManyRequests {
-			return resp, errorTooManyRequests{res: res}
+		e := errorFlushFailed{resp: res.String(), statusCode: res.StatusCode}
+		if res.StatusCode >= 400 {
```
Comment (1pkg) [inline bulk_indexer.go:355]: go-elasticsearch client treats `StatusCode > 299` as Error [here](https://github.com/elastic/go-elasticsearch/blob/v8.14.0/esapi/esapi.response.go#L92). I'm not sure how relevant handling of 3xx is, but right now any 3xx will be skipped in [here](https://github.com/elastic/go-docappender/pull/177/files#diff-e8795b30d8c0f7710cb5b474d8333d8ffacaadc4a577bbae4a8c1c2a732f4f30R362)

File: appender_test.go [hunk 5]
```diff
@@ -671,67 +671,60 @@ func TestAppenderFlushBytes(t *testing.T) {
...
+		wantStats := docappender.Stats{
+			Added:                  1,
+			Active:                 0,
+			BulkRequests:           1,
+			Failed:                 1,
+			AvailableBulkRequests:  10,
+			BytesTotal:             bytesTotal,
+			BytesUncompressedTotal: bytesUncompressedTotal,
+		}
+		if sc >= 400 {
```
Comment (1pkg) [inline appender_test.go:703]: nit: single flat switch case is better than nested if blocks

**Review by 1pkg — APPROVED** [review]

File: bulk_indexer.go (hunk 4 above)
Comment (carsonip) [inline bulk_indexer.go:355]: nit: can we have the switch case here as well? I find it more readable than nested if. Here we'll get the added benefit of fewer return statements.

**Review by carsonip — APPROVED** [review]

**Comment by carsonip** [comment]
## Testing notes

:heavy_check_mark: test-plan-ok

No change in monitoring metrics (as in `monitoring.enabled`). Metrics on failed documents surfaced in instrumentation (as in `instrumentation.enabled`, otel push-based) metrics `elasticsearch.events.processed` with corresponding `labels.status`.

Setup: Tested with local apm-server with instrumentation 8.15.0 vs upcoming 8.15.1 (8.15 branch) with mocked ES, sending to ESS apm-server

<details><summary>mock ES code</summary>
<p>
```go
```
</p>
</details> 

Steps:
1. start local apm-server with instrumentation (`instrumentation.environment`: 8.15.0 vs 8.15.1) sending to ESS apm-server
2. mock ES
3. send events to intake v2 endpoint
4. query ESS ES for metrics

### 8.15.0
#### query
```json
POST /metrics-*/_search
{
  "track_total_hits": false,
  "fields": [
    {
      "field": "@timestamp",
      "format": "strict_date_optional_time"
    },
    {
      "field": "labels.status"
    },
    {
      "field": "elasticsearch.events.processed"
    },
    {
      "field": "service.environment"
    }
  ],
  "size": 10,
  "version": true,
  "_source": false,
  "query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "exists": {
            "field": "labels.status"
          }
        },
        {
          "term": {
            "service.environment": "8.15.0"
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```

### result
```json
{
  "took": 9,
  "timed_out": false,
  "_shards": {
    "total": 23,
    "successful": 23,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "max_score": 0,
    "hits": [
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "BdZ0s5EBNgfusvAWuylZ",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.0"
          ],
          "@timestamp": [
            "2024-09-02T15:57:26.531Z"
          ],
          "elasticsearch.events.processed": [
            4
          ],
          "labels.status": [
            "Success"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "wNZzs5EBNgfusvAW0Cj2",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.0"
          ],
          "@timestamp": [
            "2024-09-02T15:56:26.526Z"
          ],
          "elasticsearch.events.processed": [
            4
          ],
          "labels.status": [
            "Success"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "e9Zys5EBNgfusvAW5iiZ",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.0"
          ],
          "@timestamp": [
            "2024-09-02T15:55:26.520Z"
          ],
          "elasticsearch.events.processed": [
            4
          ],
          "labels.status": [
            "Success"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "N9Zxs5EBNgfusvAW1ShN",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.0"
          ],
          "@timestamp": [
            "2024-09-02T15:54:26.515Z"
          ],
          "elasticsearch.events.processed": [
            4
          ],
          "labels.status": [
            "Success"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "8tZws5EBNgfusvAW6ifm",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.0"
          ],
          "@timestamp": [
            "2024-09-02T15:53:26.509Z"
          ],
          "elasticsearch.events.processed": [
            4
          ],
          "labels.status": [
            "Success"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "rdZws5EBNgfusvAWACeC",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.0"
          ],
          "@timestamp": [
            "2024-09-02T15:52:26.504Z"
          ],
          "elasticsearch.events.processed": [
            4
          ],
          "labels.status": [
            "Success"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "aNZvs5EBNgfusvAWFicc",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.0"
          ],
          "@timestamp": [
            "2024-09-02T15:51:26.498Z"
          ],
          "elasticsearch.events.processed": [
            4
          ],
          "labels.status": [
            "Success"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "I9Zus5EBNgfusvAWUie6",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.0"
          ],
          "@timestamp": [
            "2024-09-02T15:50:26.492Z"
          ],
          "elasticsearch.events.processed": [
            14
          ],
          "labels.status": [
            "Success"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "yNZts5EBNgfusvAWaCZX",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.0"
          ],
          "@timestamp": [
            "2024-09-02T15:49:26.486Z"
          ],
          "elasticsearch.events.processed": [
            4
          ],
          "labels.status": [
            "Success"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "f9Zss5EBNgfusvAWfSb3",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.0"
          ],
          "@timestamp": [
            "2024-09-02T15:48:26.479Z"
          ],
          "elasticsearch.events.processed": [
            8
          ],
          "labels.status": [
            "Success"
          ]
        }
      }
    ]
  }
}
```


### 8.15.1
#### query
```json
POST /metrics-*/_search
{
  "track_total_hits": false,
  "fields": [
    {
      "field": "@timestamp",
      "format": "strict_date_optional_time"
    },
    {
      "field": "labels.status"
    },
    {
      "field": "elasticsearch.events.processed"
    },
    {
      "field": "service.environment"
    }
  ],
  "size": 10,
  "version": true,
  "_source": false,
  "query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "exists": {
            "field": "labels.status"
          }
        },
        {
          "term": {
            "service.environment": "8.15.1"
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```

#### result
```json
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 23,
    "successful": 23,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "max_score": 0,
    "hits": [
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "69Z6s5EBNgfusvAWuCqd",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.1"
          ],
          "@timestamp": [
            "2024-09-02T16:04:08.997Z"
          ],
          "elasticsearch.events.processed": [
            5
          ],
          "labels.status": [
            "FailedClient"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "7NZ6s5EBNgfusvAWuCqd",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.1"
          ],
          "@timestamp": [
            "2024-09-02T16:04:08.997Z"
          ],
          "elasticsearch.events.processed": [
            4
          ],
          "labels.status": [
            "FailedServer"
          ]
        }
      },
      {
        "_index": ".ds-metrics-apm.app.apm_server-default-2024.09.02-000001",
        "_id": "7dZ6s5EBNgfusvAWuCqd",
        "_version": 1,
        "_score": 0,
        "fields": {
          "service.environment": [
            "8.15.1"
          ],
          "@timestamp": [
            "2024-09-02T16:04:08.997Z"
          ],
          "elasticsearch.events.processed": [
            10
          ],
          "labels.status": [
            "Success"
          ]
        }
      }
    ]
  }
}
```
